/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StarkPrice: {
      address:
        "0x048a8e979997cd8179b5c30931e12754cc5346cf4131628509de76afc66d0e93",
      abi: [
        {
          type: "impl",
          name: "StarkImpl",
          interface_name: "contracts::cryptos::StarkPrice::IStarkPrice",
        },
        {
          type: "interface",
          name: "contracts::cryptos::StarkPrice::IStarkPrice",
          items: [],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::cryptos::StarkPrice::StarkPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
    BitcoinPrice: {
      address:
        "0x00f506a6d508cbbf05c9820d3dfcec7843b63d84032d2247afb5bdadcd6ea3af",
      abi: [
        {
          type: "impl",
          name: "BitcoinImpl",
          interface_name: "contracts::cryptos::BitcoinPrice::IBitcoinPrice",
        },
        {
          type: "interface",
          name: "contracts::cryptos::BitcoinPrice::IBitcoinPrice",
          items: [],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::cryptos::BitcoinPrice::BitcoinPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
    EtherPrice: {
      address:
        "0x03efb75cdfbbaf34408e66ec588b61c526cf63c11dbd472efb70c2462f7f0792",
      abi: [
        {
          type: "impl",
          name: "EtherImpl",
          interface_name: "contracts::cryptos::EtherPrice::IEtherPrice",
        },
        {
          type: "interface",
          name: "contracts::cryptos::EtherPrice::IEtherPrice",
          items: [],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::cryptos::EtherPrice::EtherPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
