/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StarkPrice: {
      address:
        "0x012d9f5ded08e6d8d4e15f5fe7ac8e1b6baf41ec186bb6a5c6733f2a1dbede84",
      abi: [
        {
          type: "impl",
          name: "StarkImpl",
          interface_name: "contracts::cryptos::StarkPrice::IStarkPrice",
        },
        {
          type: "interface",
          name: "contracts::cryptos::StarkPrice::IStarkPrice",
          items: [],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::cryptos::StarkPrice::StarkPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
    BitcoinPrice: {
      abi: [
        {
          type: "impl",
          name: "BitcoinImpl",
          interface_name: "contracts::cryptos::BitcoinPrice::IBitcoinPrice",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::cryptos::BitcoinPrice::IBitcoinPrice",
          items: [
            {
              type: "function",
              name: "vote_yes",
              inputs: [
                {
                  name: "amount_eth",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "end_date",
              type: "core::integer::u64",
            },
            {
              name: "vote_date_limit",
              type: "core::integer::u64",
            },
            {
              name: "reference_token_price",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::cryptos::BitcoinPrice::BitcoinPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
    EtherPrice: {
      address:
        "0x01707847f6a295fb623b48ac4af847d0958e23e2de340ff50983f2c4134843c1",
      abi: [
        {
          type: "impl",
          name: "EtherImpl",
          interface_name: "contracts::cryptos::EtherPrice::IEtherPrice",
        },
        {
          type: "interface",
          name: "contracts::cryptos::EtherPrice::IEtherPrice",
          items: [],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::cryptos::EtherPrice::EtherPrice::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
